apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: xewcmyouy-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-79a5ed887f.sbhj.p3.openshiftapps.com/rhtap/rhtap-qe:c511318ca540e5ca13bbbdda4f5a14825a156cf6@sha256:83d691756e168cc76dd246d0a2efdd3f1535c772924f901f02e094eb586eec53
        name: container-image  
